config/routes.rb
Meowmates::Application.routes.draw do

  root to: 'home#index'

  devise_for :user

  # Standard GET routing.
  get "home/index"
  get 'home/get_email' => 'home#get_email'
  get "home/show" => "home#show"
  get "home/login" => "home#login"
  get "animal/get_animals" => "animal#get_animals"

  # Mailboxer

  resources :messages
  resources :conversations

  # resources :conversations, only: [:index, :show, :new, :create] do
  #   member do
  #     post :reply
  #     post :trash
  #     post :untrash
  #   end
  # end

  resources :home do
    member do
      post :new
      post :reply
      post :trash
      post :untrash
    end
  end

  resources :messages do
    member do
      post :new
    end
  end

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end

    collection do
      get :trashbin
      post :empty_trash
    end
  end

  resources :animal, :profile

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_filter :authenticate_user!
  helper_method :mailbox, :conversation

  def index
    @conversations ||= current_user.mailbox.inbox.all
  end

  def reply
    current_user.reply_to_conversation(conversation, *message_params(:body, :subject))
    redirect_to conversation
  end

  def trashbin
    @trash ||= current_user.mailbox.trash.all
  end

  def trash
    conversation.move_to_trash(current_user)
    redirect_to :conversations
  end

  def untrash
    conversation.untrash(current_user)
    redirect_to :back
  end

  def empty_trash
    current_user.mailbox.trash.each do |conversation|
      conversation.receipts_for(current_user).update_all(:deleted => true)
    end

    redirect_to :conversations
  end

  private

  def mailbox
    @mailbox ||= current_user.mailbox
  end

  def conversation
    @conversation ||= mailbox.conversations.find(params[:id])
  end

  def conversation_params(*keys)
    fetch_params(:conversation, *keys)
  end

  def message_params(*keys)
    fetch_params(:message, *keys)
  end

  def fetch_params(key, *subkeys)
    params[key].instance_eval do
      case subkeys.size
        when 0 then self
        when 1 then self[subkeys.first]
        else subkeys.map{|k| self[k] }
      end
    end
  end


end

app/views/conversations/_conversation.html.erb
<%= content_tag  :li, conversation do |conversation| %>
    <p>
      <%= link_to conversation.subject, conversation_path(conversation) %>

      <!-- if conversation.is_completely_trashed?(current_user) %>-->
        <!-- link_to "Untrash", untrash_conversation_path(conversation) %>-->
      <!-- else %>-->
        <!-- link_to "Move to Trash", trash_conversation_path(conversation) %>-->
      <!-- end %>-->
    </p>
<% end %>

app/views/conversations/_form.html.erb
<%= form_for(:conversations, url: :conversations) do |f| %>
    <%= f.input :recipients %>
    <%= f.input :subject %>
    <%= f.input :body, as: :text %>
    <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/conversations/_show.html.erb
<h4>Conversation Subject</h4>
<ul class="list-group">
  <%= content_tag_for(:li, conversation.receipts_for(current_user)) do |receipt| %>
      <%= mesage = receipt.message %>
      <h4><%= message.subject %></h4>
      <p><%= mesage.body %></p>
      <%= render "messages/form", conversation: conversation %>
  <% end %>
</ul>

app/views/conversations/index.html.erb
<div class="row">
    <h4>Conversations</h4>
    <span class="label label-info">Inbox</span>
    <%= render collection: mailbox.inbox, partial: "conversation" %>
    <span class="label label-info">Sentbox</span>
    <%= render collection: mailbox.sentbox, partial: "conversations/conversation" %>
    <span class="label label-danger">Trash</span>
    <%= render collection: mailbox.trash, partial: "conversations/conversation" %>

    <%= link_to "Start Conversation", :new_conversation %>
</div>