config/routes.rb
Meowmates::Application.routes.draw do

  root to: 'home#index'

  devise_for :user

  # Standard GET routing.
  get "home/index"
  get 'home/get_email' => 'home#get_email'
  get "home/show" => "home#show"
  get "home/login" => "home#login"
  get "animal/get_animals" => "animal#get_animals"

  # Mailboxer

  resources :messages
  resources :conversations

  # resources :conversations, only: [:index, :show, :new, :create] do
  #   member do
  #     post :reply
  #     post :trash
  #     post :untrash
  #   end
  # end

  resources :home do
    member do
      post :new
      post :reply
      post :trash
      post :untrash
    end
  end

  resources :messages do
    member do
      post :new
    end
  end

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end

    collection do
      get :trashbin
      post :empty_trash
    end
  end

  resources :animal, :profile

end

app/views/shared/_currentUser.html.erb
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>

</body>
</html>

app/views/shared/_login_modal.html.erb
<div class="modal fade" id="mod_login">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h3>Login</h3>
      </div>
     <div class="modal-body">
       <%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
            <div class="form-group">
              <%= f.text_field :email, :id => 'txt_username_login', :class => 'form-control', :placeholder => 'Username' %>
            </div>
            <div class="form-group">
              <%= f.password_field :password, :id => 'txt_password_login', :class => 'form-control', :placeholder => 'Password' %>
            </div>
            <div class="form-group">
              <%= f.check_box :remember_me %>
              <%= f.label :remember_me %>
            </div>
        </div>
        <div class="modal-footer mod-footer-color">
            <%= f.submit :Login, :id => 'btn_login', :class => 'btn btn-success' %>
            <%= link_to "Forgot your password?", new_password_path(:user) %>
        <% end %>
        </div>
     </div>
  </div>
</div>

app/views/shared/_profile_form.html.erb
    <div class="form-group">
        <%= f.text_field :first_name, :class => 'form-control',  :placeholder => 'First Name' %>
    </div>
    <div class="form-group">
        <%= f.text_field :last_name, :class => 'form-control', :placeholder => 'Last Name' %>
    </div>
    <div class="form-group">
        <%= f.text_field :gender, :class => 'form-control', :placeholder => 'Gender' %>
    </div>
    <div class="form-group">
    <%= f.text_field :birth_date, :class => 'form-control', :placeholder => 'Birth Date ##/##/####' %>
    </div>
    <div class="form-group">
      <%= f.text_field :address, :class => 'form-control', :placeholder => 'Street Address' %>
    </div>
    <div class="form-group">
      <%= f.text_field :city, :class => 'form-control', :placeholder => 'City' %>
    </div>
    <div class="form-group">
      <%= f.text_field :state, :class => 'form-control', :placeholder => 'State' %>
    </div>
    <div class="form-group">
      <%= f.text_field :zip, :class => 'form-control', :placeholder => 'Zipcode' %>
    </div>
    <div class="form-group">
      <%= f.text_field :country, :class => 'form-control', :placeholder => 'Country' %>
    </div>
    <div class="form-group">
      Are you a breeder? <%= f.check_box :breeder, :class => 'checkbox' %>
    </div>

app/views/shared/_sign_up_modal.html.erb
<div class="modal fade" id="mod_SignUp">
  <div class="modal-dialog">
    <div class="modal-content">
      <div id="user" class="registration-modal-body small-top-spacer">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h3>Step 1 - Sign Up</h3>
          <p>Create your user name and password. We promise to only user your e-mail to MeowMates official business.</p>
        </div>
        <%= form_for(resource,:id => "signup_form", :as => resource_name, :url => registration_path(resource_name)) do |f| %>
            <div class="label label-danger" id="lbl_error"></div>
                <div class="label label-success" id="lbl_success"></div>
                <div class="form-group">
                    <div class='row small-topdown-spacer'>
                        <label id="lbl_error_email" class='label label-danger'></label>
                </div>
                    <%= f.email_field :email, :id => 'txt_email', :class => 'form-control', :placeholder => 'E-mail'%>
                </div>
                <div class="form-group">
                    <label id="lbl_error_password" class="label label-danger small-topdown-spacer"></label>
                    <%= f.password_field :password, :id => 'txt_password', :class => 'form-control', :placeholder => 'Password' %>
                </div>
                <div class="form-group">
                    <label id="lbl_error_password_confirmation" class="label label-danger small-topdown-spacer"></label>
                    <%= f.password_field :password_confirmation, :id => 'txt_confirm_password', :class => 'form-control', :placeholder => 'Confirm Password' %>
                </div>
            </div>
            <div id="profile" class="registration-modal-body small-top-spacer">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h3>Step 2 - Create your Profile</h3>
                <p>Final step! Create your profile. This will serve as your MeowMates profile that you can use to browse the site, post animals
                  and find your purrfect MeowMate.</p>
              </div>
            <%= f.fields_for :Profile do |pf| %>
                <%= render :partial => "shared/profile_form", :locals => { :f => pf } %>
              <% end %>
            </div>
            <div class="modal-footer mod-footer-color">
              <ol class="mod-signup-indicators">
                <li class="active">
                  <a href="#user" style="display:none;">user</a>
                </li>
                <li>
                  <a href="#profile" style="display:none;" >Profile</a>
                </li>
              </ol>
              <%= f.submit :Submit, :id => 'btn_Submit', :class => 'btn btn-success'  %>
           <% end %>
        </div>
     </div>
  </div>
</div>


<script>

    $(document).ready(function () {
        $('.mod-signup-indicators li:first-child').on('click', function () {
            $('.mod-signup-indicators li:first-child').addClass('active');
            $('.mod-signup-indicators li:last-child').removeClass('active');
            target = $(this).find('a').attr('href');
            // the .not() makes it so if we are on that page, it doesn't fade in and out the same content
            $('.registration-modal-body:visible').not(target).fadeOut('slow', function () {
                // after we fade out old content, fade in new
                $(target).fadeIn('slow');
            });
        });

        $('.mod-signup-indicators li:last-child').on('click', function () {
            $('.mod-signup-indicators li:first-child').removeClass('active');
            $('.mod-signup-indicators li:last-child').addClass('active');
            target = $(this).find('a').attr('href');
            // the .not() makes it so if we are on that page, it doesn't fade in and out the same content
            $('.registration-modal-body:visible').not(target).fadeOut('slow', function () {
                // after we fade out old content, fade in new
                $(target).fadeIn('slow');
            });
        });
    });
</script>