config/routes.rb
Meowmates::Application.routes.draw do

  root to: 'home#index'

  devise_for :user

  # Standard GET routing.
  get "home/index"
  get 'home/get_email' => 'home#get_email'
  get "home/show" => "home#show"
  get "home/login" => "home#login"
  get "animal/get_animals" => "animal#get_animals"

  # Mailboxer

  resources :messages
  resources :conversations

  # resources :conversations, only: [:index, :show, :new, :create] do
  #   member do
  #     post :reply
  #     post :trash
  #     post :untrash
  #   end
  # end

  resources :home do
    member do
      post :new
      post :reply
      post :trash
      post :untrash
    end
  end

  resources :messages do
    member do
      post :new
    end
  end

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end

    collection do
      get :trashbin
      post :empty_trash
    end
  end

  resources :animal, :profile

end

app/models/animal.rb
class Animal < ActiveRecord::Base
  belongs_to :profile
  has_one  :profile
  has_many :breeds

  validates :full_name, presence: true
  validates :profile_id, presence: true
  validates :age,
            presence: true,
            length: {minimum: 1, maximum: 3 }
  validates :gender,
             presence: true,
             length: {minimum: 4, maximum: 6 }
            :purr_factor
            :weight
            :height
            :length
            :fixed
            :shots
            :papers
            :animal_image_content_type
            :animal_image_file_name
  validates :animal_desc,
            presence: true,
            length: {minimum: 140 }
            :breed_id

  has_attached_file :animal_image,
                    :style => {:medium => "300x300>", :thumb => "100x100>"},
                    :storage => :s3,
                    :bucket  => "purrrbucket",
                    :s3_credentials => {
                        :bucket  => "purrrbucket",
                        :access_key_id => ENV["access_key_id"],
                        :secret_access_key => ENV["secret_access_key"]
                    },
                    :s3_permissions => "private",
                    :url => ":s3_domain_url"
                    Paperclip::Attachment.default_options[:url] = ":s3_domain_url"
                    Paperclip::Attachment.default_options[:path] = "/:class/:attachment/:id_partition/:style/:filename"

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :animal_image, :content_type => /\Aimage\/.*\Z/

end

app/controllers/animal_controller.rb
class AnimalController < ApplicationController
  before_filter :new, :only => :create

  def index
    @animal = Animal.limit(8).order('RANDOM()')
  end

  def new
    @arr_gender = ['Male','Female']
    @breeds = Breeds.all
    @age = ['1','2','3','4','5','6','7','8']
    @animal = Animal.new
  end

  def show
    @animal = Animal.find(params[:id])
  end

  def create
    @animal = Animal.new(animal_params)
    respond_to do |format|
        if @animal.save
          flash[:notice] = "#{@animal.full_name} has been added to your profile."
          format.json { render json: @animal, status: :created, location: @animal }
          format.html { render "animal/index" }
        else
          flash.now[:error] = @animal.errors.full_messages
          format.html { render action: "new" }
          format.json { render json: @animal.errors, status: :unprocessable_entity }
        end
      end
  end

  def get_animals()
    @animal = Animal.limit(8).order('RANDOM()')

    respond_to do |format|
      if @animal.present?
        format.js {}
        format.json { render json: @animal }
      else
        format.js {}
        flash[:error] = @animal.errors.full_messages
        format.json { render json: @animals.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def animal_params

    params.require(:animal).permit(:full_name, :profile_id, :age, :gender, :purr_factor, :weight, :height,
                                                :length, :fixed, :shots, :papers, :animal_desc, :breed_id, :animal_image)
  end
end

app/helpers/animal_helper.rb
module AnimalHelper
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/views/animal/_cat_card.html.erb
<div class="row">
      <% i = 0 %>
        <% @animal.each do |a| %>
          <% i += 1 %>
          <% if i <= 4 %>
            <div class="col-sm-3" >
                <div class="cat-card">
                    <%= link_to image_tag("cat_banner.jpg", :class => 'cat-img img-circle cat-card-img') %>
                    <h3 class="cat-name"><%= a.full_name %></h3>
                    Age: <%= a.age %>
                    <span class="clearfix" />
                    Gender: <%= a.gender %>
                    <span class="clearfix" />
                    Breed: <%= a.breed_id %>
                    <span class="clearfix" />
                    <span class="padding-top-bottom-10"></span>
                  <%= button_to "Details", animal_path(a), :class => "btn btn-card", :method => "get" %>
                </div>
            </div>
        <% else %>
            <div class="col-sm-3 padding-top-250">
                <div class="cat-card">
                  <%= link_to image_tag("cat_banner.jpg", :class => 'cat-img img-circle cat-card-img') %>
                  <h3 class="cat-name"><%= a.full_name %></h3>
                  Age: <%= a.age %>
                  <span class="clearfix" />
                  Gender: <%= a.gender %>
                  <span class="clearfix" />
                  Breed: <%= a.breed_id %>
                  <span class="clearfix" />
                  <span class="padding-top-bottom-10"></span>
                  <%= button_to "Details", animal_path(a), :class => "btn btn-card", :method => "get" %>
                </div>
            </div>
        <% end %>
    <% end %>
</div>

app/views/animal/_form.html.erb
<div class="container-fluid">
  <div class="row padding-top-15 border-bottom">
    <div class="col-sm-1 visible-lg visible-md">
      <%= image_tag("create_animal_banner_small.png", :class => "img-circle cat-banner") %>
    </div>
    <div class="col-sm-offset-2">
        <h3 class="orange">
            Create your pets Profile
        </h3>
      <p class="padding-right">With your profile your pet can browse other profiles and find the mate of his dreams.</p>
    </div>
  </div>
  <hr/>
  <div class="row">
    <div class="col-md-5">

        <%= form_for(@animal, :url => {:controller => "animal", :action => "create"}, :html => {:multipart => true} ) do |f| %>
        <!-- Error Handling -->
          <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
            <% if @animal.errors.any? %>
                <div id="error_explanation">
                    <ul>
                        <% @animal.errors.full_messages.each do |msg| %>
                            <li><%= msg %></li>
                        <% end %>
                    </ul>
                </div>
            <% end %>
          <!-- FORM -->
          <h4 class="orange">General Info</h4>
          <div class="form-group">
            <%= f.label :full_name %>
            <%= f.text_field :full_name, :id => "txt_full_name", :class => "form-control medium-text-input", :placeholder => "Full Name" %>
            <%= f.hidden_field :profile_id, :value => '1' %>
          </div>
          <div class="form-group">
            <div class="btn-group">
              <button id="btn_age" type="button" class="btn dropdown-toggle" data-toggle="dropdown">
                <%= f.label :age %>
                <span class="caret"></span>
              </button>
              <ul id="menu_age" class="dropdown-menu" role="menu">
                <% @age.each do |a| %>
                    <li><a data-value="<%= a %>" href="#<%= a %>"><%= a %></a></li>
                <% end %>
                <%= f.hidden_field(:age, :value => "", :class => 'hidden', :id => "hidden_age") %>
              </ul>
            </div>
          </div>
          <div class="form-group">
            <div class="btn-group">
              <button id="btn_gender" type="button" class="btn dropdown-toggle" data-toggle="dropdown">
                    <%= f.label :gender %>
                <span class="caret"></span>
              </button>
              <ul id="menu_gender" class="dropdown-menu" role="menu">
                <% @arr_gender.each do |g| %>
                    <li><a data-value="<%= g %>" href="#<%= g %>"><%= g %></a></li>
                <% end %>
                <%= f.hidden_field(:gender, :value => "", :class => 'hidden', :id => "hidden_gender") %>
              </ul>
            </div>
          </div>
          <div class="form-group">
             <%= f.label :weight %>
             <%= f.text_field :weight, :class => 'form-control small-text-input', :placeholder => 'Weight' %>
            in pounds
          </div>
          <div class="form-group">
             <%= f.label :height %>
            <%= f.text_field :height, :class => 'form-control small-text-input', :placeholder => 'Height' %>
            in inches
          </div>
          <div class="form-group">
            <%= f.label :length %>
            <%= f.text_field :length, :class => 'form-control small-text-input', :placeholder => 'Length' %>
            in inches
          </div>
      </div>
      <div class="col-md-5">
        <h4 class="orange">Mixed or Purebred</h4>
          <div class="form-group">
            <div class="btn-group">
              <button id="btn_breed" type="button" class="btn dropdown-toggle" data-toggle="dropdown">
                <%= f.label "Breeds" %> <span class="caret"></span>
              </button>
              <ul id="menu_breeds" class="dropdown-menu" role="menu">
                <% @breeds.each do |b| %>
                    <li><a data-value="<%= b.id %>" href="#<%= b.id %>"><%= b.breed_name %></a></li>
                <% end %>
                <%=f.hidden_field(:breed_id, :value => "", :class => 'hidden', :id => 'hidden_breed') %>
              </ul>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :papers %>
            <%= f.check_box :papers, :class => "checkbox" %>
          </div>
          <h4 class="orange">Medical Info</h4>
          <div class="form-group">
            <%= f.label :fixed %>
            <%= f.check_box :fixed, :class => "checkbox" %>
          </div>
          <div class="form-group">
            <%= f.label :shots %>
            <%= f.check_box :shots, :class => "checkbox" %>
          </div>
        <div class="row padding-top-bottom-10"></div>

        <h4 class="orange">Upload your Pets Photos!</h4>
        <div class="form-group padding-top-bottom-10">
          <%= f.file_field :animal_image %>
          <div class="row padding-top-bottom-10"></div>
        </div>
        </div>
        </div>
        <div class="peachbox">
          <h4 class="orange">Tell Us About Your Pet</h4>
          <p>Here is your chance to tell us about your pet.</p>
          <%= f.text_area :animal_desc, :class => "form-control" %>
          <div class="row padding-top-bottom-10"></div>
          <%= f.submit :Meow!, :id => "btn_CreateAnimal", :class => "btn btn-success" %>
        </div>
    <% end %>
</div>

<script>

    //TODO: Rewrite in Coffee. Can't believe I forgot. Gay.
    //TODO: Finish dynamic solution.
    //TODO: Try snippet in dynamic code.
    //$this.addClass("select").siblings().removeClass("select");

    $(document).ready(function () {
        //var menu_id
        $('.dropdown-toggle').dropdown();

        // Dynamic
        //    $('.dropdown-menu').hover(function (){
        //        console.log(menu_id = $(this).attr('id'));
        //        var menu_id = $(this).closest('ul').attr('id');
        //    });

        //    $('.dropdown-menu li a').click(function(){
        //        var id = $('.btn:first-child').attr('id');
        //        $('#'+id).text($(this).text());
        //        $('#'+id).val($(this).text());
        //
        //        //$('.btn:first-child').val($(this).text());
        //    });

        // Boring
        $('#menu_gender li a').click(function () {
            $('#btn_gender').text($(this).text());
            $('#btn_gender').val($(this).text());
            $(this).addClass('active');
        });

        $('#menu_breeds li a').click(function () {
            $('#btn_breed').text($(this).text());
            $('#btn_breed').val($(this).text());
            $(this).addClass('active');
        });

        $('#menu_age li a').click(function () {
            $('#btn_age').text($(this).text());
            $('#btn_age').val($(this).text());
            $(this).addClass('active');
        });

    });

</script>

app/views/animal/create.html.erb
<%= stylesheet_link_tag "animalGallery.css" %>

app/views/animal/index.html.erb
<%= stylesheet_link_tag "animalGallery.css" %>

<div id="animal-container" class="container-fluid padding-50">

  <%= render partial: 'cat_card',:object => @animal %>

</div>

app/views/animal/new.html.erb
<%= stylesheet_link_tag "animalGallery.css" %>

<%= render partial: 'form',:object => @animal %>

app/views/animal/show.html.erb
<%= stylesheet_link_tag "animalGallery.css" %>

<div class="container-fluid">
  <h2><%= @animal.full_name %>'s Purrrfile</h2>
  <div class="row">
        <div class="col-sm-6 padding-top-bottom-30">
          <%= link_to image_tag("cat_banner.jpg", :class => "img-rounded main-animalprofile-image") %>
        </div>
    <section class="col-sm-offset-6 padding-top-bottom-30">
      <ul class="list-group">
        <li class="list-group-item-heading list-unstyled"><%= @animal.full_name %></li>
        <li class="list-group-item">
          Age: <%= @animal.age %>
        </li>
        <li class="list-group-item">
          Weight: <%= @animal.weight %>
        </li>
        <li class="list-group-item">
          Height: <%= @animal.height %>
        </li>
        <li class="list-group-item">
          Length: <%= @animal.length %>
        </li>
        <li class="list-group-item">
          Fixed:  <%= @animal.fixed %>
        </li>
        <li class="list-group-item">
          Shots:  <%= @animal.shots %>
        </li>
        <li class="list-group-item">
          Papers  <%= @animal.papers %>
        </li>
      </ul>
    </section>
    <div class="col-sm-12 padding-top-bottom-30">
      About Me: <%= @animal.animal_desc %>
    </div>
  </div>
</div>